when:
  - event: cron
    cron: renovate
  - event: manual
  - event: pull_request
  - event: push
    branch: main
  - event: tag
    ref: refs/tags/v*

steps:
  - name: test
    image: nimlang/nim:2.2.4
    commands:
      - nimble test -y
    when:
      - event: pull_request
      - event: push
        branch: main
      - event: tag
        ref: refs/tags/v*

  - name: build
    image: nimlang/nim:2.2.4
    commands:
      - nimble buildRelease -y
      - cp build/posixglob-basic build/posixglob-basic-linux-amd64
    depends_on:
      - test
    when:
      - event: pull_request
      - event: push
        branch: main
      - event: tag
        ref: refs/tags/v*

  - name: release
    image: woodpeckerci/plugin-release:0.3.1
    settings:
      api-key:
        from_secret: github_token
      files:
        - build/posixglob-basic-linux-amd64
        - LICENSE
        - NOTICE
      file-exists: overwrite
      generate-release-notes: true
      title: ${CI_COMMIT_TAG}
    depends_on:
      - build
    when:
      - event: tag
        ref: refs/tags/v*

  - name: renovate
    image: renovate/renovate:latest
    commands:
      - renovate "$CI_REPO"
    environment:
      RENOVATE_PLATFORM: github
      RENOVATE_TOKEN:
        from_secret: renovate_token
    when:
      - event: cron
        cron: renovate
      - event: manual
